apiVersion: v1
kind: Namespace
metadata:
  name: gremlin
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: gremlin
  namespace: gremlin
  labels:
    k8s-app: gremlin
    version: v1
spec:
  template:
    metadata:
      labels:
        k8s-app: gremlin
        version: v1
    spec:
      containers:
        - name: gremlin
          image: gremlin/gremlin
          args: ['daemon']
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_BOOT
                - SYS_TIME
                - KILL
          env:
            - name: GREMLIN_ORG_ID
              value: <YOUR TEAM ID>
            - name: GREMLIN_ORG_SECRET
              value: <YOUR SECRET KEY>
            - name: GREMLIN_IDENTIFIER
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
